#Mobs
kill @e[tag=!named,type=minecraft:zombie]
kill @e[tag=!named,type=minecraft:zombie_pigman]
kill @e[tag=!named,type=minecraft:skeleton]
kill @e[tag=!named,type=minecraft:enderman]
#Blocks
kill @e[type=item,name="dirt"]
kill @e[type=item,name="cobblestone"]
kill @e[type=item,name="cobbled deepslate"]
kill @e[type=item,name="deepslate"]
kill @e[type=item,name="stone"]
kill @e[type=item,name="andesite"]
kill @e[type=item,name="calcite"]
kill @e[type=item,name="netherrack"]
kill @e[type=item,name="sand"]
kill @e[type=item,name="granite"]
kill @e[type=item,name="gravel"]
kill @e[type=item,name="tuff"]
#Items
kill @e[type=item,name="gold ingot"]
kill @e[type=item,name="gold nuget"]
kill @e[type=item,name="golden sword"]
kill @e[type=item,name="redstone"]
kill @e[type=item,name="raw iron"]
kill @e[type=item,name="iron nugget"]
kill @e[type=item,name="raw gold"]
kill @e[type=item,name="poppy"]
kill @e[type=item,name="nether quartz"]
kill @e[type=item,name="lapis lazuli"]
kill @e[type=item,name="rotten flesh"]